# $FML: mk.conf,v 1.38 2024/05/15 08:42:42 fukachan Exp $

# use pkgsrc as could as possible.

# 2020(?)-, PKG_DBDIR is required.
PKG_DBDIR=/var/db/pkg

# new on NetBSD 2.0* (and may be true on 3.0 after). 
# 2020/01/01 - , disabled PREFER_PKGSRC, native by default.
# PREFER_PKGSRC=yes
# X11_TYPE=modular
# PTHREAD_TYPE=native
EMACS_TYPE=emacs25nox

# builddir
WRKOBJDIR=/var/tmp/pkgsrc.work

# not download binary packages.
#BINPKG_SITES=ftp://ftp.fml.org/dist/pkgsrc-prefer-binary/$${rel}/$${arch}
BINPKG_SITES=

# local hack ?
READLINE_DEFAULT=readline

#
EMACS_TYPE=emacs26nox

# exception
PKG_OPTIONS.ng= -canna
PKG_OPTIONS.mencoder=faad
PKG_OPTIONS.mplayer= -pulseaudio -sdl
PKG_OPTIONS.apache22=suexec
PKG_OPTIONS.apache24=suexec -http2
PKG_OPTIONS.apache=suexec -http2
PKG_OPTIONS.squid= -squid-pam-helper
PKG_OPTIONS.samba= -pam
PKG_OPTIONS.gd= -libvpx
PKG_OPTIONS.gmake= -nls
PKG_OPTIONS.gnuplot= -cerf -gd -gnuplot-pdf-doc


#
# licenses
#
ACCEPTABLE_LICENSES+=adobe-acrobat-license
ACCEPTABLE_LICENSES+=djb-nonlicense
ACCEPTABLE_LICENSES+=eclipse-license
ACCEPTABLE_LICENSES+=fee-based-commercial-use
ACCEPTABLE_LICENSES+=flash-license
ACCEPTABLE_LICENSES+=idea-license
ACCEPTABLE_LICENSES+=iozone-license
ACCEPTABLE_LICENSES+=kermit-license
ACCEPTABLE_LICENSES+=lame-license
ACCEPTABLE_LICENSES+=lha-license
ACCEPTABLE_LICENSES+=mplayer-codec-license
ACCEPTABLE_LICENSES+=ms-ttf-license
ACCEPTABLE_LICENSES+=openmotif-license
ACCEPTABLE_LICENSES+=openssl
ACCEPTABLE_LICENSES+=pgp5-license
ACCEPTABLE_LICENSES+=postfix-license
ACCEPTABLE_LICENSES+=rar-license
ACCEPTABLE_LICENSES+=sendmail-license
ACCEPTABLE_LICENSES+=skype-license
ACCEPTABLE_LICENSES+=sun-jdk6-license
ACCEPTABLE_LICENSES+=sun-jre6-license
ACCEPTABLE_LICENSES+=unrar-license
ACCEPTABLE_LICENSES+=xv-license
ACCEPTABLE_LICENSES+=gnu-agpl-v3

# wireless firmware
ACCEPTABLE_LICENSES+=intel-ipw-license
ACCEPTABLE_LICENSES+=nvidia-firmware-license



#
# licenses local
#
